[project]
name = "mcp_server_ppt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[project.scripts]
mcp-server-ppt = "mcp_server_ppt.ppt:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"